name: Publish

on:
  repository_dispatch:
    types: [trigger-workflow]
  workflow_dispatch:

jobs:
  all:
    runs-on: ubuntu-latest
    container:
      image: rocker/r-ver:4.3.1
    steps:

      - name: Invoke workflow sisor-2026
        uses: the-actions-org/workflow-dispatch@v4
        with:
          workflow: all.yaml
          repo: splor-mg/dados-armazem-siafi-2025
          ref: main
          token: "${{ secrets.GH_PAT }}"
          wait-for-completion: true

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache R packages
        uses: actions/cache@v4
        with:
          path: renv/library
          key: ${{ runner.os }}-R-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-R-

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Setup
        run: |
          /rocker_scripts/install_python.sh
          export DEBIAN_FRONTEND=noninteractive
          apt-get update && apt-get install -y git libcurl4-openssl-dev libssl-dev libsodium-dev
          echo 'alias python=python3' >> /etc/bash.bashrc
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install -r requirements.txt
          Rscript -e "install.packages('renv')" && Rscript -e 'renv::restore()'

      - name: ETL
        env:
          MS365_KEY: ${{ secrets.MS365_KEY }}
        run: |
          make all

      - name: Deploy to GitHub pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          clean: false
          branch: gh-pages
          folder: .
